apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata: 
      labels: 
        app: frontend
    spec:
      containers:
       - name: frontend-app
         image: frontend
         ports:
          - containerPort: 80
         envFrom:
          - configMapRef:
              name: frontend-config
