apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata: 
      labels: 
        app: frontend
    spec:
      containers:
       - name: frontend-app
         image: 440422120931.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-frontend:latest
         ports:
          - containerPort: 80
         envFrom:
          - configMapRef:
              name: frontend-config
